digital-bank:
  service:
    runtime-profile: sit

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-service-openapi
              uri: http://customer-service:8081
              predicates:
                - Path=/customer-service/v3/api-docs
              filters:
                - RewritePath=/customer-service/(?<segment>.*), /$\{segment}
            - id: customer-service
              uri: http://customer-service:8081
              predicates:
                - Path=/api/v1/customers/**
