digital-bank:
  service:
    runtime-profile: sit

auth:
  jwt:
    issuer: digital-bank-auth
    secret: ${AUTH_JWT_SECRET:}

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/transaction_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: kafka.digital-bank-sit.svc.cluster.local:9092
    properties:
      security.protocol: PLAINTEXT

transaction:
  events:
    reservation:
      enabled: true
      sit-plaintext-enabled: true
      kafka:
        bootstrap-servers: kafka.digital-bank-sit.svc.cluster.local:9092
      security:
        protocol: PLAINTEXT
