digital-bank:
  service:
    runtime-profile: sit

auth:
  jwt:
    audience: payment-service

spring:
  kafka:
    bootstrap-servers: kafka.digital-bank-sit.svc.cluster.local:9092
    properties:
      security.protocol: PLAINTEXT

payment:
  events:
    topic: payment.instruction.state.v1
